
package Negocio;

import Presentacion.AdmModificador;
import Dato.cancion;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MusicaAdm extends javax.swing.JFrame {
    DefaultTableModel modelo;
  
    public MusicaAdm() {
        initComponents();
        //Center window
        setLocationRelativeTo(null);
        //The table and the name of each column are declared
        modelo= new DefaultTableModel();
        modelo.addColumn("Genero");
        modelo.addColumn("Cantante");
        modelo.addColumn("Nombre de la cancion");
        modelo.addColumn("Cantidad de discos");
        this.tablaMusic.setModel(modelo);
        //Give color to the background of the jFrame
        this.getContentPane().setBackground(Color.pink);
        
    }

    MusicaAdm(AdmModificador aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGeneroM = new javax.swing.JTextField();
        txtCantante = new javax.swing.JTextField();
        txtxCancion = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMusic = new javax.swing.JTable();
        btnModi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCantDis = new javax.swing.JTextField();
        btnEli = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Genero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Cantante");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setText("Nombre de la cancion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        getContentPane().add(txtGeneroM, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 260, 30));
        getContentPane().add(txtCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 260, 40));
        getContentPane().add(txtxCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 230, 40));

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, 40));

        tablaMusic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaMusic);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 480, 380));

        btnModi.setText("Modificar");
        btnModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiActionPerformed(evt);
            }
        });
        getContentPane().add(btnModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 100, 40));

        jLabel4.setText("Cantidad de discos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 120, 30));
        getContentPane().add(txtCantDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 220, 30));

        btnEli.setText("Eliminar");
        btnEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliActionPerformed(evt);
            }
        });
        getContentPane().add(btnEli, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 100, 40));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        //The information entered is added to the table
        String [] Datos= new String[4];
        Datos[0]=txtGeneroM.getText();
        txtGeneroM.setText(null);
        Datos[1]=txtCantante.getText();
        txtCantante.setText(null);
        Datos[2]=txtxCancion.getText();
        txtxCancion.setText(null);
        Datos[3]= txtCantDis.getText();
        txtCantDis.setText(null);
        modelo.addRow(Datos);
        
        
        String gen = txtxCancion.getText();
        String can = txtCantante.getText();
        String nomCan = txtxCancion.getText();
        String cantDis = txtCantDis.getText();
        cancion nuevaCancion = new cancion(gen, can, nomCan, Integer.parseInt(cantDis));
        nuevaCancion.agregarCancion();

        JOptionPane.showMessageDialog(null, "Se agrego la musica correctamente");
        
        
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiActionPerformed
        //A row is selected to modify it
        int FilaSelec= tablaMusic.getSelectedRow();
        
        
        if (FilaSelec >= 0){
            txtGeneroM.setText(tablaMusic.getValueAt(FilaSelec, 0).toString());
            txtCantante.setText(tablaMusic.getValueAt(FilaSelec, 1).toString());
            txtxCancion.setText(tablaMusic.getValueAt(FilaSelec, 2).toString());
            txtCantDis.setText(tablaMusic.getValueAt(FilaSelec, 3).toString());
        }else
            //If none is selected, it is notified
            JOptionPane.showMessageDialog(this, "Fila no selecciona");
    }//GEN-LAST:event_btnModiActionPerformed

    private void btnEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliActionPerformed
        // A row is selected to remove it
        int FilaSelecEli = tablaMusic.getSelectedRow();
        if (FilaSelecEli >= 0){
            modelo.removeRow(FilaSelecEli);
            
        }else
            //If none is selected, it is notified
            JOptionPane.showMessageDialog(this, "Fila no selecciona");
    }//GEN-LAST:event_btnEliActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        //Declared empty to clean the txt of the interface
        txtGeneroM.setText("");
        txtCantante.setText("");
        txtxCancion.setText("");
        txtCantDis.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnEli;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMusic;
    private javax.swing.JTextField txtCantDis;
    private javax.swing.JTextField txtCantante;
    private javax.swing.JTextField txtGeneroM;
    private javax.swing.JTextField txtxCancion;
    // End of variables declaration//GEN-END:variables
}
