
package Negocio;

import Dato.pelicula;
import Dato.persona;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class PeliculasAdm extends javax.swing.JFrame {
    DefaultTableModel modeloPelicula;
    
    public PeliculasAdm() {
        initComponents();
        //Center window
        setLocationRelativeTo(null);
        //The table and the name of each column are declared
        modeloPelicula= new DefaultTableModel();
        modeloPelicula.addColumn("Genero");
        modeloPelicula.addColumn("Autor");
        modeloPelicula.addColumn("Nombre de la pelicula");
        modeloPelicula.addColumn("Cantidad de discos");
        this.tablaPelis.setModel(modeloPelicula);
        //Give color to the background of the jFrame
        this.getContentPane().setBackground(Color.pink);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPelis = new javax.swing.JTable();
        txtxGeneroP = new javax.swing.JTextField();
        txtxAutor = new javax.swing.JTextField();
        txtPeli = new javax.swing.JTextField();
        txtCantPeli = new javax.swing.JTextField();
        btnAgragarP = new javax.swing.JButton();
        btnLimpiarP = new javax.swing.JButton();
        btnModiP = new javax.swing.JButton();
        btnEliP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Genero");

        jLabel2.setText("Autor");

        jLabel3.setText("Nombre pelicula");

        jLabel4.setText("Cantidad de discos");

        tablaPelis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPelis);

        btnAgragarP.setText("Agregar");
        btnAgragarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgragarPActionPerformed(evt);
            }
        });

        btnLimpiarP.setText("Limpiar");
        btnLimpiarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPActionPerformed(evt);
            }
        });

        btnModiP.setText("Modificar");
        btnModiP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiPActionPerformed(evt);
            }
        });

        btnEliP.setText("Eliminar");
        btnEliP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtxGeneroP, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtxAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgragarP)
                        .addGap(30, 30, 30)
                        .addComponent(btnLimpiarP)
                        .addGap(52, 52, 52)
                        .addComponent(btnModiP)
                        .addGap(50, 50, 50)
                        .addComponent(btnEliP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtxGeneroP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtxAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtCantPeli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgragarP)
                    .addComponent(btnLimpiarP)
                    .addComponent(btnModiP)
                    .addComponent(btnEliP))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgragarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgragarPActionPerformed
        ////The information entered is added to the table
        String [] Datos= new String[3];
        Datos[0]=txtxGeneroP.getText();
        txtxGeneroP.setText(null);
        Datos[1]=txtxAutor.getText();
        txtxAutor.setText(null);
        Datos[2] = txtPeli.getText();
        txtCantPeli.setText(null);
        Datos[3] = txtCantPeli.getText();
        txtCantPeli.setText(null);
        modeloPelicula.addRow(Datos);

        String gen = txtxGeneroP.getText();
        String aut = txtxAutor.getText();
        String nomPeli = txtPeli.getText();
        String cantDis = txtCantPeli.getText();
        pelicula nuevaPelicula = new pelicula(gen, aut, nomPeli, Integer.parseInt(cantDis));
        nuevaPelicula.agregarPelicula();

        JOptionPane.showMessageDialog(null, "Se agrego la pelicula correctamente");
    }//GEN-LAST:event_btnAgragarPActionPerformed

    private void btnLimpiarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPActionPerformed
       //Declared empty to clean the txt of the interface
        txtxGeneroP.setText("");
        txtxAutor.setText("");
        txtPeli.setText("");
        txtCantPeli.setText("");
    }//GEN-LAST:event_btnLimpiarPActionPerformed

    private void btnModiPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiPActionPerformed
        //A row is selected to modify it
        int FilaSelec= tablaPelis.getSelectedRow();
        if (FilaSelec >= 0){
            txtxGeneroP.setText(tablaPelis.getValueAt(FilaSelec, 0).toString());
            txtxAutor.setText(tablaPelis.getValueAt(FilaSelec, 1).toString());
            txtPeli.setText(tablaPelis.getValueAt(FilaSelec, 2).toString());
            txtCantPeli.setText(tablaPelis.getValueAt(FilaSelec, 3).toString());
        }else
        //If none is selected, it is notified
            JOptionPane.showMessageDialog(this, "Fila no selecciona");
    }//GEN-LAST:event_btnModiPActionPerformed

    private void btnEliPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliPActionPerformed
        // A row is selected to remove it
        int FilaSelecEli = tablaPelis.getSelectedRow();
        if (FilaSelecEli >= 0){
            modeloPelicula.removeRow(FilaSelecEli);
            
        }else
            //If none is selected, it is notified
            JOptionPane.showMessageDialog(this, "Fila no selecciona");
    }//GEN-LAST:event_btnEliPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeliculasAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeliculasAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeliculasAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeliculasAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeliculasAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgragarP;
    private javax.swing.JButton btnEliP;
    private javax.swing.JButton btnLimpiarP;
    private javax.swing.JButton btnModiP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPelis;
    private javax.swing.JTextField txtCantPeli;
    private javax.swing.JTextField txtPeli;
    private javax.swing.JTextField txtxAutor;
    private javax.swing.JTextField txtxGeneroP;
    // End of variables declaration//GEN-END:variables
}
