/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Negocio.RegistrarUsuario;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Sileny Araya
 */
public class LoginUsu extends javax.swing.JFrame {

    /** Creates new form LoginUsu */
    public LoginUsu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pssUsuario = new javax.swing.JPasswordField();
        BtnRegUsu = new javax.swing.JButton();
        btnEntrarUsu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 30));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 190, 30));
        getContentPane().add(pssUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 190, 30));

        BtnRegUsu.setText("Registrarse");
        BtnRegUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegUsuActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 110, 40));

        btnEntrarUsu.setText("Entrar");
        btnEntrarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarUsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 255, 80, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/discos.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegUsuActionPerformed
        RegistrarUsuario ventanaRegistro = new RegistrarUsuario();
        ventanaRegistro.pack();
        ventanaRegistro.setVisible(true);
    }//GEN-LAST:event_BtnRegUsuActionPerformed

    public boolean verify(String user, String pass)
    {
         try {
            
            try (BufferedReader bf = new BufferedReader(new FileReader("Usuarios.txt"))) {
                String bfRead;
                while ((bfRead = bf.readLine()) != null) {
                    String[] datos = bfRead.split(",");
                    if(datos[0].equals(user) && datos[1].equals(pass)){
                        return true;
                    }
                   
                }
            }
        } catch (IOException e) {
            System.out.println("No se encontro el archivo" + e);
        }
        return false;
    }       
    private void btnEntrarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarUsuActionPerformed
        if (verify(txtUsuario.getText(), pssUsuario.getText())) {
            System.out.println("Bienvenido");
      
        
        MenuPrincipal ventanaSecundaria= new MenuPrincipal();
        ventanaSecundaria.pack();
        ventanaSecundaria.setVisible(true);
        } else{
            JOptionPane.showMessageDialog(null, "Usuario incorrecto, intente de nuevo");
        }

        
    }//GEN-LAST:event_btnEntrarUsuActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegUsu;
    private javax.swing.JButton btnEntrarUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pssUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
